import { expect, test, type Page } from '@playwright/test'

async function enterDemo(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Open demo' }).click()
  await expect(page.getByRole('heading', { name: 'Save the good stuff.' })).toBeVisible()
}

test('sign in form is keyboard-friendly and exposes useful errors', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByLabel('Account action').getByRole('button', { name: 'Sign in' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Email').fill('demo@mosaic.local')
  await page.getByLabel('Password', { exact: true }).fill('wrong-password')
  await page.getByLabel('Password', { exact: true }).press('Enter')
  await expect(page.getByRole('alert')).toHaveText('Email or password is incorrect.')
  await page.getByRole('button', { name: 'Show password' }).click()
  await expect(page.getByLabel('Password', { exact: true })).toHaveAttribute('type', 'text')
})

test('expired sessions return to auth and do not leak cached account data', async ({ page }) => {
  await enterDemo(page)
  await page.getByRole('link', { name: 'Collections', exact: true }).click()
  await expect(page.getByRole('link', { name: /Museum of small things/ })).toBeVisible()
  await page.evaluate(async () => {
    await fetch('/api/auth/logout', { method: 'POST' })
  })
  await page.goto('/collections/smart/recent')
  await expect(page.getByRole('heading', { name: 'Pick up where you left off.' })).toBeVisible()

  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Fresh Account')
  await page.getByLabel('Email').fill(`fresh-${Date.now()}@example.test`)
  await page.getByLabel('Password', { exact: true }).fill('fresh-password')
  await page.getByLabel('Password', { exact: true }).press('Enter')
  await expect(page.getByRole('heading', { name: 'Recently saved' })).toBeVisible()
  await expect(page.getByText('Nothing here yet.')).toBeVisible()
  await page.getByRole('link', { name: 'Collections', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Collections' })).toBeVisible()
  await expect(page.getByRole('link', { name: /Museum of small things/ })).toHaveCount(0)
})

test('reviewer can move through the core product', async ({ page }) => {
  await enterDemo(page)
  const search = page.getByLabel('Search images')
  await expect(search).toBeVisible()
  await search.focus()
  await expect(search).toBeFocused()
  const focusShadow = await page.locator('.discover-search').evaluate((element) => getComputedStyle(element).boxShadow)
  expect(focusShadow).not.toBe('none')

  await page.getByRole('link', { name: 'Collections' }).click()
  await expect(page.getByRole('heading', { name: 'Collections' })).toBeVisible()
  await page.getByRole('link', { name: /Museum of small things/ }).click()
  await expect(page.getByRole('heading', { name: 'Museum of small things' })).toBeVisible()
  await page.getByRole('tab', { name: /Canvas/ }).click()
  await expect(page.getByText('Make it yours.')).toBeVisible()
  await page.getByRole('button', { name: 'Remix board' }).click()
  await expect(page.getByText('Board remixed')).toBeVisible()

  await page.getByRole('link', { name: 'Explore' }).click()
  await expect(page.getByRole('heading', { name: 'What people are saving.' })).toBeVisible()
  const firstPin = page.locator('.public-pin-image').first()
  await expect(firstPin).toBeVisible()
  await firstPin.click()
  await expect(page.locator('.pin-page-card')).toBeVisible()
  await expect(page.getByRole('button', { name: /like/i })).toBeVisible()
})

test('mobile shell stays usable at 390px', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await enterDemo(page)
  const searchBox = await page.getByLabel('Search images').boundingBox()
  expect(searchBox?.height ?? 0).toBeGreaterThanOrEqual(40)
  await expect(page.locator('.mobile-nav')).toBeVisible()
  await page.getByRole('link', { name: 'Explore' }).last().click()
  await expect(page.getByRole('heading', { name: 'What people are saving.' })).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  expect(overflow).toBeLessThanOrEqual(1)
  await page.goto('/collections/2')
  const back = await page.getByRole('link', { name: 'All collections' }).boundingBox()
  expect(back?.height ?? 0).toBeGreaterThanOrEqual(32)
  const sharing = page.getByRole('button', { name: 'Manage sharing' })
  if (await sharing.count()) {
    const box = await sharing.boundingBox()
    expect(box?.height ?? 0).toBeGreaterThanOrEqual(32)
  }
})

test('new account can create, capture, edit, share, revoke and undo', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Reviewer')
  await page.getByLabel('Email').fill(`reviewer-${Date.now()}@example.test`)
  await page.getByLabel('Password', { exact: true }).fill('reviewer-password')
  await page.getByLabel('Password', { exact: true }).press('Enter')
  await expect(page.getByRole('heading', { name: 'Save the good stuff.' })).toBeVisible()
  await page.getByRole('button', { name: 'Dismiss quick tour' }).click()
  await page.getByRole('link', { name: 'Collections', exact: true }).click()
  await page.getByRole('button', { name: 'New collection', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Reviewer board')
  await page.getByRole('button', { name: 'Create collection', exact: true }).last().click()
  await page.getByRole('link', { name: /Reviewer board/ }).click()
  const boardUrl = page.url()
  await page.goto('/capture')
  await page.getByLabel('Image URL', { exact: true }).fill('https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=500')
  await page.getByLabel('Title', { exact: true }).fill('Reviewer reference')
  await page.getByRole('textbox', { name: 'Note', exact: true }).fill('Remember this / composition')
  await page.getByRole('button', { name: 'Save to Mosaic' }).click()
  await expect(page.locator('.saved-card')).toContainText('Remember this / composition')
  await page.locator('.saved-card').getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('Note', { exact: true }).fill('Edited / note')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.locator('.saved-card')).toContainText('Edited / note')
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  await page.getByRole('button', { name: 'Public', exact: true }).click()
  const link = page.locator('.share-url')
  await expect(link).toBeVisible()
  const token = (await link.innerText()).split('/shared/')[1]
  const guest = await browser.newContext()
  const publicPage = await guest.newPage()
  await publicPage.goto(`http://127.0.0.1:3199/shared/${token}`)
  await expect(publicPage.getByRole('heading', { name: 'Reviewer board' })).toBeVisible()
  await page.getByRole('button', { name: 'Private', exact: true }).click()
  await expect(page.getByText('Only collaborators can open this collection while it is private.')).toBeVisible()
  await publicPage.reload()
  await expect(publicPage.getByText('This share link is no longer available.')).toBeVisible()
  await guest.close()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.locator('.saved-card').getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.locator('.saved-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.saved-card')).toContainText('Edited / note')
  await page.reload()
  await expect(page.locator('.saved-card')).toContainText('Edited / note')
  expect(page.url()).toBe(boardUrl)
})

test('canvas keyboard focus survives persistence and failed saves roll back', async ({ page }) => {
  await enterDemo(page)
  await page.getByRole('button', { name: 'Dismiss quick tour' }).click()
  await page.goto('/collections/2')
  await page.getByRole('tab', { name: 'Canvas' }).click()
  const pin = page.locator('.canvas-item').first()
  await pin.focus()
  const initial = await pin.getAttribute('style')
  const saved = page.waitForResponse((response) => response.url().endsWith('/layout') && response.status() === 204)
  await pin.press('ArrowRight')
  await saved
  await expect(pin).toBeFocused()
  await expect(pin).not.toHaveAttribute('style', initial!)
  await page.route('**/api/collections/2/layout', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Test save unavailable' }) }))
  const before = await pin.getAttribute('style')
  await pin.press('ArrowRight')
  await expect(page.getByText('Test save unavailable')).toBeVisible()
  await expect(pin).toHaveAttribute('style', before!)
})

test('390px capture, dialog focus and offline reload have usable recovery', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await enterDemo(page)
  await page.getByRole('button', { name: 'Dismiss quick tour' }).click()
  await page.locator('.mobile-nav').getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Save something new.' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Note', exact: true }).fill('a/b')
  await page.getByRole('textbox', { name: 'Note', exact: true }).press('/')
  await expect(page.getByRole('textbox', { name: 'Note', exact: true })).toHaveValue('a/b/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await page.evaluate(() => navigator.serviceWorker.ready)
  // Reload under the active worker before simulating a cold offline navigation.
  await page.reload()
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Connect to Mosaic' })).toBeVisible()
  await context.setOffline(false)
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('heading', { name: 'Save something new.' })).toBeVisible()
})
